/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from '../../node_modules/ngx-bootstrap/dropdown/bs-dropdown-container.component.ngfactory';
import * as i4 from './bio/bio.component.ngfactory';
import * as i5 from './texts/random.component.ngfactory';
import * as i6 from './texts/random-en.component.ngfactory';
import * as i7 from './texts/text-nocturine.component.ngfactory';
import * as i8 from './texts/text-nocturine1.component.ngfactory';
import * as i9 from './texts/text-nocturine2.component.ngfactory';
import * as i10 from './texts/text-nocturine3.component.ngfactory';
import * as i11 from './texts/text-nocturine1en.component.ngfactory';
import * as i12 from './texts/text-nocturine2en.component.ngfactory';
import * as i13 from './texts/text-nocturine3en.component.ngfactory';
import * as i14 from './texts/text-cunninghamella1.component.ngfactory';
import * as i15 from './texts/text-cunninghamella2.component.ngfactory';
import * as i16 from './texts/text-cunninghamella3.component.ngfactory';
import * as i17 from './texts/text-cunninghamella1en.component.ngfactory';
import * as i18 from './texts/text-vostok1.component.ngfactory';
import * as i19 from './texts/text-vostok2.component.ngfactory';
import * as i20 from './texts/text-vostok3.component.ngfactory';
import * as i21 from './texts/text-vostok4.component.ngfactory';
import * as i22 from './texts/text-vostok1en.component.ngfactory';
import * as i23 from './texts/text-vostok2en.component.ngfactory';
import * as i24 from './texts/text-vostok3en.component.ngfactory';
import * as i25 from './texts/text-vostok4en.component.ngfactory';
import * as i26 from './texts/text-biegnacyczlowiek.component.ngfactory';
import * as i27 from './texts/text-wszystkozernosc.component.ngfactory';
import * as i28 from './texts/text-cmy.component.ngfactory';
import * as i29 from './texts/text-moths.component.ngfactory';
import * as i30 from './texts/text-obrovsky.component.ngfactory';
import * as i31 from './texts/text-obrovskyen.component.ngfactory';
import * as i32 from './app.component.ngfactory';
import * as i33 from '@angular/common';
import * as i34 from '@angular/platform-browser';
import * as i35 from 'ngx-bootstrap/positioning/positioning.service';
import * as i36 from 'ngx-bootstrap/component-loader/component-loader.factory';
import * as i37 from 'ngx-bootstrap/dropdown/bs-dropdown.state';
import * as i38 from '@angular/router';
import * as i39 from 'ngx-bootstrap/dropdown/bs-dropdown.module';
import * as i40 from './bio/bio.component';
import * as i41 from './texts/random.component';
import * as i42 from './texts/random-en.component';
import * as i43 from './texts/text-nocturine.component';
import * as i44 from './texts/text-nocturine1.component';
import * as i45 from './texts/text-nocturine2.component';
import * as i46 from './texts/text-nocturine3.component';
import * as i47 from './texts/text-nocturine1en.component';
import * as i48 from './texts/text-nocturine2en.component';
import * as i49 from './texts/text-nocturine3en.component';
import * as i50 from './texts/text-cunninghamella1.component';
import * as i51 from './texts/text-cunninghamella2.component';
import * as i52 from './texts/text-cunninghamella3.component';
import * as i53 from './texts/text-cunninghamella1en.component';
import * as i54 from './texts/text-vostok1.component';
import * as i55 from './texts/text-vostok2.component';
import * as i56 from './texts/text-vostok3.component';
import * as i57 from './texts/text-vostok4.component';
import * as i58 from './texts/text-vostok1en.component';
import * as i59 from './texts/text-vostok2en.component';
import * as i60 from './texts/text-vostok3en.component';
import * as i61 from './texts/text-vostok4en.component';
import * as i62 from './texts/text-biegnacyczlowiek.component';
import * as i63 from './texts/text-wszystkozernosc.component';
import * as i64 from './texts/text-cmy.component';
import * as i65 from './texts/text-moths.component';
import * as i66 from './texts/text-obrovsky.component';
import * as i67 from './texts/text-obrovskyen.component';
import * as i68 from 'ngx-bootstrap/dropdown/bs-dropdown.config';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.BsDropdownContainerComponentNgFactory,i4.BioComponentNgFactory,i5.RandomComponentNgFactory,
              i6.RandomEnComponentNgFactory,i7.TextNocturineComponentNgFactory,i8.TextNocturine1ComponentNgFactory,
              i9.TextNocturine2ComponentNgFactory,i10.TextNocturine3ComponentNgFactory,
              i11.TextNocturine1EnComponentNgFactory,i12.TextNocturine2EnComponentNgFactory,
              i13.TextNocturine3EnComponentNgFactory,i14.TextCunninghamella1ComponentNgFactory,
              i15.TextCunninghamella2ComponentNgFactory,i16.TextCunninghamella3ComponentNgFactory,
              i17.TextCunninghamella1EnComponentNgFactory,i18.TextVostok1ComponentNgFactory,
              i19.TextVostok2ComponentNgFactory,i20.TextVostok3ComponentNgFactory,
              i21.TextVostok4ComponentNgFactory,i22.TextVostok1EnComponentNgFactory,
              i23.TextVostok2EnComponentNgFactory,i24.TextVostok3EnComponentNgFactory,
              i25.TextVostok4EnComponentNgFactory,i26.TextBiegnacyczlowiekComponentNgFactory,
              i27.TextWszystkozernoscComponentNgFactory,i28.TextCmyComponentNgFactory,
              i29.TextMothsComponentNgFactory,i30.TextObrovskyComponentNgFactory,i31.TextObrovskyEnComponentNgFactory,
              i32.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i33.NgLocalization,
              i33.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,
              ([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),
          i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),i0.ɵmpd(4608,i34.DomSanitizer,
              i34.ɵe,[i33.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i34.DomSanitizer]),
          i0.ɵmpd(4608,i34.HAMMER_GESTURE_CONFIG,i34.HammerGestureConfig,([] as any[])),
          i0.ɵmpd(5120,i34.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
            return [new i34.ɵDomEventsPlugin(p0_0),new i34.ɵKeyEventsPlugin(p1_0),
                new i34.ɵHammerGesturesPlugin(p2_0,p2_1)];
          },[i33.DOCUMENT,i33.DOCUMENT,i33.DOCUMENT,i34.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i34.EventManager,i34.EventManager,[i34.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i34.ɵDomSharedStylesHost,i34.ɵDomSharedStylesHost,[i33.DOCUMENT]),
          i0.ɵmpd(4608,i34.ɵDomRendererFactory2,i34.ɵDomRendererFactory2,[i34.EventManager,
              i34.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i34.ɵDomRendererFactory2]),i0.ɵmpd(6144,i34.ɵSharedStylesHost,(null as any),
              [i34.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i34.Meta,i34.Meta,[i33.DOCUMENT]),i0.ɵmpd(4608,
              i34.Title,i34.Title,[i33.DOCUMENT]),i0.ɵmpd(4608,i35.PositioningService,
              i35.PositioningService,([] as any[])),i0.ɵmpd(4608,i36.ComponentLoaderFactory,
              i36.ComponentLoaderFactory,[i0.ComponentFactoryResolver,i0.NgZone,i0.Injector,
                  i35.PositioningService,i0.ApplicationRef]),i0.ɵmpd(4608,i37.BsDropdownState,
              i37.BsDropdownState,([] as any[])),i0.ɵmpd(5120,i38.ActivatedRoute,i38.ɵf,
              [i38.Router]),i0.ɵmpd(4608,i38.NoPreloading,i38.NoPreloading,([] as any[])),
          i0.ɵmpd(6144,i38.PreloadingStrategy,(null as any),[i38.NoPreloading]),i0.ɵmpd(135680,
              i38.RouterPreloader,i38.RouterPreloader,[i38.Router,i0.NgModuleFactoryLoader,
                  i0.Compiler,i0.Injector,i38.PreloadingStrategy]),i0.ɵmpd(4608,i38.PreloadAllModules,
              i38.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i38.ROUTER_INITIALIZER,
              i38.ɵi,[i38.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i38.ROUTER_INITIALIZER]),i0.ɵmpd(512,i33.CommonModule,i33.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i34.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i38.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i38.ɵg,i38.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i34.ɵc(p0_0,p0_1),i38.ɵh(p1_0)];
              },[[2,i34.NgProbeToken],[2,i0.NgProbeToken],i38.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i34.BrowserModule,i34.BrowserModule,[[3,i34.BrowserModule]]),
          i0.ɵmpd(512,i39.BsDropdownModule,i39.BsDropdownModule,([] as any[])),i0.ɵmpd(1024,
              i38.ɵa,i38.ɵd,[[3,i38.Router]]),i0.ɵmpd(512,i38.UrlSerializer,i38.DefaultUrlSerializer,
              ([] as any[])),i0.ɵmpd(512,i38.ChildrenOutletContexts,i38.ChildrenOutletContexts,
              ([] as any[])),i0.ɵmpd(256,i38.ROUTER_CONFIGURATION,{},([] as any[])),
          i0.ɵmpd(1024,i33.LocationStrategy,i38.ɵc,[i33.PlatformLocation,[2,i33.APP_BASE_HREF],
              i38.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i33.Location,i33.Location,[i33.LocationStrategy]),
          i0.ɵmpd(512,i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i38.ROUTES,() => {
            return [[{path:'',redirectTo:'/random',pathMatch:'full'},{path:'bio',component:i40.BioComponent,
                data:{title:'Łukasz Drobnik - prozaik',theme:5}},{path:'bio/en',component:i40.BioComponent,
                data:{title:'Łukasz Drobnik - fiction writer',theme:5}},{path:'random',
                component:i41.RandomComponent,data:{title:'Łukasz Drobnik - oficjalna strona / official website',
                    theme:0}},{path:'random/en',component:i42.RandomEnComponent,data:{title:'Łukasz Drobnik - oficjalna strona / official website',
                theme:0}},{path:'nocturine',component:i43.TextNocturineComponent,data:{title:'Łukasz Drobnik - Nocturine (fragment)',
                theme:0}},{path:'nocturine1',component:i44.TextNocturine1Component,
                data:{title:'Łukasz Drobnik - Nocturine - Ośmiobitowe sny',theme:0}},
                {path:'nocturine2',component:i45.TextNocturine2Component,data:{title:'Łukasz Drobnik - Nocturine - W morskiej wnętrzności',
                    theme:0}},{path:'nocturine3',component:i46.TextNocturine3Component,
                    data:{title:'Łukasz Drobnik - Nocturine - Pejzaż z pięcioma domami',
                        theme:0}},{path:'nocturine1/en',component:i47.TextNocturine1EnComponent,
                    data:{title:'Łukasz Drobnik - Nocturine - 8-bit Dreams',theme:0}},
                {path:'nocturine2/en',component:i48.TextNocturine2EnComponent,data:{title:'Łukasz Drobnik - Nocturine - Through the Sea’s Gut',
                    theme:0}},{path:'nocturine3/en',component:i49.TextNocturine3EnComponent,
                    data:{title:'Łukasz Drobnik - Nocturine - Landscape with Five Houses',
                        theme:0}},{path:'cunninghamella1',component:i50.TextCunninghamella1Component,
                    data:{title:'Łukasz Drobnik - Cunninghamella - Rozdział trzeci',
                        theme:1}},{path:'cunninghamella2',component:i51.TextCunninghamella2Component,
                    data:{title:'Łukasz Drobnik - Cunninghamella - Rozdział dziesiąty',
                        theme:1}},{path:'cunninghamella3',component:i52.TextCunninghamella3Component,
                    data:{title:'Łukasz Drobnik - Cunninghamella - Rozdział dwunasty',
                        theme:1}},{path:'cunninghamella1/en',component:i53.TextCunninghamella1EnComponent,
                    data:{title:'Łukasz Drobnik - Cunninghamella - Chapter Three',
                        theme:1}},{path:'vostok1',component:i54.TextVostok1Component,
                    data:{title:'Łukasz Drobnik - Vostok - Rozdział pierwszy',theme:2}},
                {path:'vostok2',component:i55.TextVostok2Component,data:{title:'Łukasz Drobnik - Vostok - Rozdział drugi',
                    theme:2}},{path:'vostok3',component:i56.TextVostok3Component,data:{title:'Łukasz Drobnik - Vostok - Rozdział trzeci',
                    theme:2}},{path:'vostok4',component:i57.TextVostok4Component,data:{title:'Łukasz Drobnik - Vostok - Rozdział czwarty',
                    theme:2}},{path:'vostok1/en',component:i58.TextVostok1EnComponent,
                    data:{title:'Łukasz Drobnik - Vostok - Chapter One',theme:2}},
                {path:'vostok2/en',component:i59.TextVostok2EnComponent,data:{title:'Łukasz Drobnik - Vostok - Chapter Two',
                    theme:2}},{path:'vostok3/en',component:i60.TextVostok3EnComponent,
                    data:{title:'Łukasz Drobnik - Vostok - Chapter Three',theme:2}},
                {path:'vostok4/en',component:i61.TextVostok4EnComponent,data:{title:'Łukasz Drobnik - Vostok - Chapter Four',
                    theme:2}},{path:'biegnacyczlowiek',component:i62.TextBiegnacyczlowiekComponent,
                    data:{title:'Łukasz Drobnik - Biegnący człowiek',theme:3}},{path:'wszystkozernosc',
                    component:i63.TextWszystkozernoscComponent,data:{title:'Łukasz Drobnik - Wszystkożerność',
                        theme:3}},{path:'cmy',component:i64.TextCmyComponent,data:{title:'Łukasz Drobnik - Ćmy',
                    theme:4}},{path:'moths/en',component:i65.TextMothsComponent,data:{title:'Łukasz Drobnik - Moths',
                    theme:4}},{path:'obrovsky',component:i66.TextObrovskyComponent,
                    data:{title:'Łukasz Drobnik - Obrovsky - Wszystko, co podziemne',
                        theme:5}},{path:'obrovsky/en',component:i67.TextObrovskyEnComponent,
                    data:{title:'Łukasz Drobnik - Obrovsky - All Things Subterranean',
                        theme:5}},{path:'**',redirectTo:'/random'}]];
          },([] as any[])),i0.ɵmpd(1024,i38.Router,i38.ɵe,[i0.ApplicationRef,i38.UrlSerializer,
              i38.ChildrenOutletContexts,i33.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i38.ROUTES,i38.ROUTER_CONFIGURATION,[2,i38.UrlHandlingStrategy],
              [2,i38.RouteReuseStrategy]]),i0.ɵmpd(512,i38.RouterModule,i38.RouterModule,
              [[2,i38.ɵa],[2,i38.Router]]),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[])),
          i0.ɵmpd(256,i68.BsDropdownConfig,{autoClose:true},([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovd2ViZGV2L2x1a2Fzei1kcm9ibmlrLmNvbS9sdWthc3otZHJvYm5pay5jb20vYXNzZXRzL2FwcC9hcHAubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0U6L3dlYmRldi9sdWthc3otZHJvYm5pay5jb20vbHVrYXN6LWRyb2JuaWsuY29tL2Fzc2V0cy9hcHAvYXBwLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
