/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from '../../node_modules/ngx-bootstrap/dropdown/bs-dropdown-container.component.ngfactory';
import * as i4 from './bio/bio.component.ngfactory';
import * as i5 from './texts/random.component.ngfactory';
import * as i6 from './texts/random-en.component.ngfactory';
import * as i7 from './texts/text-nocturine3.component.ngfactory';
import * as i8 from './texts/text-nocturine3en.component.ngfactory';
import * as i9 from './texts/text-cunninghamella1.component.ngfactory';
import * as i10 from './texts/text-cunninghamella1en.component.ngfactory';
import * as i11 from './texts/text-vostok1.component.ngfactory';
import * as i12 from './texts/text-vostok1en.component.ngfactory';
import * as i13 from './texts/text-wszystkozernosc.component.ngfactory';
import * as i14 from './texts/text-cmy.component.ngfactory';
import * as i15 from './texts/text-moths.component.ngfactory';
import * as i16 from './texts/text-obrovsky.component.ngfactory';
import * as i17 from './texts/text-obrovskyen.component.ngfactory';
import * as i18 from './app.component.ngfactory';
import * as i19 from '@angular/common';
import * as i20 from '@angular/platform-browser';
import * as i21 from 'ngx-bootstrap/positioning/positioning.service';
import * as i22 from 'ngx-bootstrap/component-loader/component-loader.factory';
import * as i23 from 'ngx-bootstrap/dropdown/bs-dropdown.state';
import * as i24 from '@angular/router';
import * as i25 from 'ngx-bootstrap/dropdown/bs-dropdown.module';
import * as i26 from './bio/bio.component';
import * as i27 from './texts/random.component';
import * as i28 from './texts/random-en.component';
import * as i29 from './texts/text-nocturine3.component';
import * as i30 from './texts/text-nocturine3en.component';
import * as i31 from './texts/text-cunninghamella1.component';
import * as i32 from './texts/text-cunninghamella1en.component';
import * as i33 from './texts/text-vostok1.component';
import * as i34 from './texts/text-vostok1en.component';
import * as i35 from './texts/text-wszystkozernosc.component';
import * as i36 from './texts/text-cmy.component';
import * as i37 from './texts/text-moths.component';
import * as i38 from './texts/text-obrovsky.component';
import * as i39 from './texts/text-obrovskyen.component';
import * as i40 from 'ngx-bootstrap/dropdown/bs-dropdown.config';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.BsDropdownContainerComponentNgFactory,i4.BioComponentNgFactory,i5.RandomComponentNgFactory,
              i6.RandomEnComponentNgFactory,i7.TextNocturine3ComponentNgFactory,i8.TextNocturine3EnComponentNgFactory,
              i9.TextCunninghamella1ComponentNgFactory,i10.TextCunninghamella1EnComponentNgFactory,
              i11.TextVostok1ComponentNgFactory,i12.TextVostok1EnComponentNgFactory,
              i13.TextWszystkozernoscComponentNgFactory,i14.TextCmyComponentNgFactory,
              i15.TextMothsComponentNgFactory,i16.TextObrovskyComponentNgFactory,i17.TextObrovskyEnComponentNgFactory,
              i18.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i19.NgLocalization,
              i19.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,
              ([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),
          i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),i0.ɵmpd(4608,i20.DomSanitizer,
              i20.ɵe,[i19.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i20.DomSanitizer]),
          i0.ɵmpd(4608,i20.HAMMER_GESTURE_CONFIG,i20.HammerGestureConfig,([] as any[])),
          i0.ɵmpd(5120,i20.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
            return [new i20.ɵDomEventsPlugin(p0_0),new i20.ɵKeyEventsPlugin(p1_0),
                new i20.ɵHammerGesturesPlugin(p2_0,p2_1)];
          },[i19.DOCUMENT,i19.DOCUMENT,i19.DOCUMENT,i20.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i20.EventManager,i20.EventManager,[i20.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i20.ɵDomSharedStylesHost,i20.ɵDomSharedStylesHost,[i19.DOCUMENT]),
          i0.ɵmpd(4608,i20.ɵDomRendererFactory2,i20.ɵDomRendererFactory2,[i20.EventManager,
              i20.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i20.ɵDomRendererFactory2]),i0.ɵmpd(6144,i20.ɵSharedStylesHost,(null as any),
              [i20.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i20.Meta,i20.Meta,[i19.DOCUMENT]),i0.ɵmpd(4608,
              i20.Title,i20.Title,[i19.DOCUMENT]),i0.ɵmpd(4608,i21.PositioningService,
              i21.PositioningService,([] as any[])),i0.ɵmpd(4608,i22.ComponentLoaderFactory,
              i22.ComponentLoaderFactory,[i0.ComponentFactoryResolver,i0.NgZone,i0.Injector,
                  i21.PositioningService,i0.ApplicationRef]),i0.ɵmpd(4608,i23.BsDropdownState,
              i23.BsDropdownState,([] as any[])),i0.ɵmpd(5120,i24.ActivatedRoute,i24.ɵf,
              [i24.Router]),i0.ɵmpd(4608,i24.NoPreloading,i24.NoPreloading,([] as any[])),
          i0.ɵmpd(6144,i24.PreloadingStrategy,(null as any),[i24.NoPreloading]),i0.ɵmpd(135680,
              i24.RouterPreloader,i24.RouterPreloader,[i24.Router,i0.NgModuleFactoryLoader,
                  i0.Compiler,i0.Injector,i24.PreloadingStrategy]),i0.ɵmpd(4608,i24.PreloadAllModules,
              i24.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i24.ROUTER_INITIALIZER,
              i24.ɵi,[i24.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i24.ROUTER_INITIALIZER]),i0.ɵmpd(512,i19.CommonModule,i19.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i20.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i24.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i24.ɵg,i24.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i20.ɵc(p0_0,p0_1),i24.ɵh(p1_0)];
              },[[2,i20.NgProbeToken],[2,i0.NgProbeToken],i24.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i20.BrowserModule,i20.BrowserModule,[[3,i20.BrowserModule]]),
          i0.ɵmpd(512,i25.BsDropdownModule,i25.BsDropdownModule,([] as any[])),i0.ɵmpd(1024,
              i24.ɵa,i24.ɵd,[[3,i24.Router]]),i0.ɵmpd(512,i24.UrlSerializer,i24.DefaultUrlSerializer,
              ([] as any[])),i0.ɵmpd(512,i24.ChildrenOutletContexts,i24.ChildrenOutletContexts,
              ([] as any[])),i0.ɵmpd(256,i24.ROUTER_CONFIGURATION,{},([] as any[])),
          i0.ɵmpd(1024,i19.LocationStrategy,i24.ɵc,[i19.PlatformLocation,[2,i19.APP_BASE_HREF],
              i24.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i19.Location,i19.Location,[i19.LocationStrategy]),
          i0.ɵmpd(512,i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i24.ROUTES,() => {
            return [[{path:'',redirectTo:'/random',pathMatch:'full'},{path:'bio',component:i26.BioComponent,
                data:{title:'Łukasz Drobnik - prozaik',theme:5}},{path:'bio/en',component:i26.BioComponent,
                data:{title:'Łukasz Drobnik - fiction writer',theme:5}},{path:'random',
                component:i27.RandomComponent,data:{title:'Łukasz Drobnik - oficjalna strona / official website',
                    theme:0}},{path:'random/en',component:i28.RandomEnComponent,data:{title:'Łukasz Drobnik - oficjalna strona / official website',
                theme:0}},{path:'nocturine',component:i29.TextNocturine3Component,
                data:{title:'Łukasz Drobnik - Nocturine (fragment)',theme:0}},{path:'nocturine/en',
                component:i30.TextNocturine3EnComponent,data:{title:'Łukasz Drobnik - Nocturine (fragment)',
                    theme:0}},{path:'cunninghamella',component:i31.TextCunninghamella1Component,
                data:{title:'Łukasz Drobnik - Cunninghamella (fragment)',theme:1}},
                {path:'cunninghamella/en',component:i32.TextCunninghamella1EnComponent,
                    data:{title:'Łukasz Drobnik - Cunninghamella (fragment)',theme:1}},
                {path:'vostok',component:i33.TextVostok1Component,data:{title:'Łukasz Drobnik - Vostok - Rozdział pierwszy',
                    theme:2}},{path:'vostok/en',component:i34.TextVostok1EnComponent,
                    data:{title:'Łukasz Drobnik - Vostok - Chapter One',theme:2}},
                {path:'wszystkozernosc',component:i35.TextWszystkozernoscComponent,
                    data:{title:'Łukasz Drobnik - Wszystkożerność',theme:3}},{path:'cmy',
                    component:i36.TextCmyComponent,data:{title:'Łukasz Drobnik - Ćmy',
                        theme:4}},{path:'moths/en',component:i37.TextMothsComponent,
                    data:{title:'Łukasz Drobnik - Moths',theme:4}},{path:'obrovsky',
                    component:i38.TextObrovskyComponent,data:{title:'Łukasz Drobnik - Obrovsky - Wszystko, co podziemne',
                        theme:5}},{path:'obrovsky/en',component:i39.TextObrovskyEnComponent,
                    data:{title:'Łukasz Drobnik - Obrovsky - All Things Subterranean',
                        theme:5}},{path:'**',redirectTo:'/random'}]];
          },([] as any[])),i0.ɵmpd(1024,i24.Router,i24.ɵe,[i0.ApplicationRef,i24.UrlSerializer,
              i24.ChildrenOutletContexts,i19.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i24.ROUTES,i24.ROUTER_CONFIGURATION,[2,i24.UrlHandlingStrategy],
              [2,i24.RouteReuseStrategy]]),i0.ɵmpd(512,i24.RouterModule,i24.RouterModule,
              [[2,i24.ɵa],[2,i24.Router]]),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[])),
          i0.ɵmpd(256,i40.BsDropdownConfig,{autoClose:true},([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovd2ViZGV2L2x1a2Fzei1kcm9ibmlrLmNvbS9fZHJvYm5pay5jby9kcm9ibmlrLmNvL2Fzc2V0cy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9FOi93ZWJkZXYvbHVrYXN6LWRyb2JuaWsuY29tL19kcm9ibmlrLmNvL2Ryb2JuaWsuY28vYXNzZXRzL2FwcC9hcHAubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
