/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './nav/nav.component.ngfactory';
import * as i3 from './nav/nav.component';
import * as i4 from '@angular/router';
import * as i5 from './app.component';
import * as i6 from '@angular/platform-browser';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-nav',([] as any[]),
      (null as any),[['window','resize']],(_v,en,$event) => {
        var ad:boolean = true;
        if (('window:resize' === en)) {
          const pd_0:any = ((<any>i1.ɵnov(_v,1).onResize($event)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },i2.View_NavComponent_0,i2.RenderType_NavComponent)),i1.ɵdid(114688,(null as any),
      0,i3.NavComponent,[i4.Router,i4.ActivatedRoute],(null as any),(null as any)),
      (_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(16777216,(null as any),
          (null as any),1,'router-outlet',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),i1.ɵdid(212992,(null as any),
          0,i4.RouterOutlet,[i4.ChildrenOutletContexts,i1.ViewContainerRef,i1.ComponentFactoryResolver,
              [8,(null as any)],i1.ChangeDetectorRef],(null as any),(null as any))],
      (_ck,_v) => {
        _ck(_v,1,0);
        _ck(_v,4,0);
      },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'my-app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(114688,(null as any),0,i5.AppComponent,[i4.Router,i4.ActivatedRoute,
          i6.Title],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i5.AppComponent> = i1.ɵccf('my-app',
    i5.AppComponent,View_AppComponent_Host_0,{langEn:'langEn'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovd2ViZGV2L2x1a2Fzei1kcm9ibmlrLmNvbS9fZHJvYm5pay5jby9kcm9ibmlrLmNvL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9FOi93ZWJkZXYvbHVrYXN6LWRyb2JuaWsuY29tL19kcm9ibmlrLmNvL2Ryb2JuaWsuY28vYXNzZXRzL2FwcC9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vRTovd2ViZGV2L2x1a2Fzei1kcm9ibmlrLmNvbS9fZHJvYm5pay5jby9kcm9ibmlrLmNvL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRTovd2ViZGV2L2x1a2Fzei1kcm9ibmlrLmNvbS9fZHJvYm5pay5jby9kcm9ibmlrLmNvL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8YXBwLW5hdj48L2FwcC1uYXY+XHJcbjxyb3V0ZXItb3V0bGV0Pjwvcm91dGVyLW91dGxldD4iLCI8bXktYXBwPjwvbXktYXBwPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtRQUFBO1FBQUE7VUFBQTtVQUFBO1FBQUE7UUFBQTtNQUFBLDZEQUFBO01BQUE7TUFBbUIsdUNBQ25CO1VBQUE7VUFBQSxtREFBQTtVQUFBO2NBQUE7O1FBREE7UUFDQTs7OztvQkNEQTtNQUFBO2FBQUE7a0JBQUE7SUFBQTs7OzsifQ==
