/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './random-en.component';
const styles_RandomEnComponent:any[] = ([] as any[]);
export const RenderType_RandomEnComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_RandomEnComponent,data:{}});
export function View_RandomEnComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,([] as any[]),(null as any),(null as any));
}
export function View_RandomEnComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'ng-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_RandomEnComponent_0,
      RenderType_RandomEnComponent)),i0.ɵdid(49152,(null as any),0,i1.RandomEnComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const RandomEnComponentNgFactory:i0.ComponentFactory<i1.RandomEnComponent> = i0.ɵccf('ng-component',
    i1.RandomEnComponent,View_RandomEnComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovd2ViZGV2L2Ryb2JuaWsgd3JpdGluZyAtIG5vd2Egc3Ryb25hL2Ryb2JuaWsuY28vYXNzZXRzL2FwcC90ZXh0cy9yYW5kb20tZW4uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L3dlYmRldi9kcm9ibmlrIHdyaXRpbmcgLSBub3dhIHN0cm9uYS9kcm9ibmlrLmNvL2Fzc2V0cy9hcHAvdGV4dHMvcmFuZG9tLWVuLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L3dlYmRldi9kcm9ibmlrIHdyaXRpbmcgLSBub3dhIHN0cm9uYS9kcm9ibmlrLmNvL2Fzc2V0cy9hcHAvdGV4dHMvcmFuZG9tLWVuLmNvbXBvbmVudC50cy5SYW5kb21FbkNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxuZy1jb21wb25lbnQ+PC9uZy1jb21wb25lbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtrQ0FBQSxVQUFBO01BQUE7OzsifQ==
