/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './random.component';
const styles_RandomComponent:any[] = ([] as any[]);
export const RenderType_RandomComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_RandomComponent,data:{}});
export function View_RandomComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,([] as any[]),(null as any),(null as any));
}
export function View_RandomComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'ng-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_RandomComponent_0,
      RenderType_RandomComponent)),i0.ɵdid(49152,(null as any),0,i1.RandomComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const RandomComponentNgFactory:i0.ComponentFactory<i1.RandomComponent> = i0.ɵccf('ng-component',
    i1.RandomComponent,View_RandomComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovd2ViZGV2L2Ryb2JuaWsgd3JpdGluZyAtIG5vd2Egc3Ryb25hL2Ryb2JuaWsuY28vYXNzZXRzL2FwcC90ZXh0cy9yYW5kb20uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L3dlYmRldi9kcm9ibmlrIHdyaXRpbmcgLSBub3dhIHN0cm9uYS9kcm9ibmlrLmNvL2Fzc2V0cy9hcHAvdGV4dHMvcmFuZG9tLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L3dlYmRldi9kcm9ibmlrIHdyaXRpbmcgLSBub3dhIHN0cm9uYS9kcm9ibmlrLmNvL2Fzc2V0cy9hcHAvdGV4dHMvcmFuZG9tLmNvbXBvbmVudC50cy5SYW5kb21Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8bmctY29tcG9uZW50PjwvbmctY29tcG9uZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7Z0NBQUEsVUFBQTtNQUFBOzs7In0=
