/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './random-en.component';
const styles_RandomEnComponent:any[] = ([] as any[]);
export const RenderType_RandomEnComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_RandomEnComponent,data:{}});
export function View_RandomEnComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,([] as any[]),(null as any),(null as any));
}
export function View_RandomEnComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'ng-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_RandomEnComponent_0,
      RenderType_RandomEnComponent)),i0.ɵdid(49152,(null as any),0,i1.RandomEnComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const RandomEnComponentNgFactory:i0.ComponentFactory<i1.RandomEnComponent> = i0.ɵccf('ng-component',
    i1.RandomEnComponent,View_RandomEnComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovd2ViZGV2L2Ryb2JuaWsgd3JpdGluZy9fZHJvYm5pa19zdHJvbmFfcGxpa2kvZHJvYm5pay5jby9hc3NldHMvYXBwL3RleHRzL3JhbmRvbS1lbi5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovd2ViZGV2L2Ryb2JuaWsgd3JpdGluZy9fZHJvYm5pa19zdHJvbmFfcGxpa2kvZHJvYm5pay5jby9hc3NldHMvYXBwL3RleHRzL3JhbmRvbS1lbi5jb21wb25lbnQudHMiLCJuZzovLy9EOi93ZWJkZXYvZHJvYm5payB3cml0aW5nL19kcm9ibmlrX3N0cm9uYV9wbGlraS9kcm9ibmlrLmNvL2Fzc2V0cy9hcHAvdGV4dHMvcmFuZG9tLWVuLmNvbXBvbmVudC50cy5SYW5kb21FbkNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxuZy1jb21wb25lbnQ+PC9uZy1jb21wb25lbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtrQ0FBQSxVQUFBO01BQUE7OzsifQ==
